// SPDX-License-Identifier: MPL-2.0
import { test, expect } from '@playwright/test';
import { serve } from '../../scripts/serve.ts';
import { readFile } from 'node:fs/promises';

const selected = process.env.FOOD_HELP_TEST_REVIEW ? JSON.parse(process.env.FOOD_HELP_TEST_REVIEW) as { directory: string; sourceDir: string } : null;

test('isolated draft review stays visibly non-public and ephemeral', async ({ browser }) => {
  test.skip(!selected, 'Review artifact is generated by the complete check workflow.');
  const server = await serve({ root: selected!.directory, port: 0, reviewDrafts: true });
  const origin = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
  const context = await browser.newContext();
  try {
    const page = await context.newPage(); const home = await page.goto(origin);
    expect(home!.headers()['cache-control']).toContain('no-store'); expect(home!.headers()['x-robots-tag']).toContain('noindex');
    await expect(page.locator('#draft-review-banner')).toBeVisible();
    await expect(page.locator('link[rel="manifest"]')).toHaveCount(0);
    await expect.poll(() => page.evaluate(async () => Boolean(await navigator.serviceWorker.getRegistration()))).toBe(false);
    expect(await page.evaluate(async () => (await caches.keys()).some(key => key.includes('data-review')))).toBe(false);
    const publicResponse = await context.request.get(`${origin}/data/v1/resources.json`), reviewResponse = await context.request.get(`${origin}/data/review/resources.json`);
    expect(publicResponse.headers()['access-control-allow-origin']).toBe('*');
    expect(reviewResponse.headers()['access-control-allow-origin']).toBeUndefined();
    const publicData = await publicResponse.json(), reviewData = await reviewResponse.json();
    expect(reviewData.resources.length).toBeGreaterThanOrEqual(publicData.resources.length);
    expect(publicData.resources.some((resource: { publication_status: string }) => resource.publication_status === 'draft')).toBe(false);
    expect(reviewData.resources.some((resource: { publication_status: string }) => resource.publication_status === 'draft')).toBe(true);
    const drafts = reviewData.resources.filter((resource: { publication_status: string }) => resource.publication_status === 'draft').length;
    await page.goto(`${origin}/directory/`); await expect(page.locator('article')).toHaveCount(reviewData.resources.length); await expect(page.locator('.draft-badge')).toHaveCount(drafts);
  } finally { await context.close(); await new Promise<void>(resolve => server.close(() => resolve())); }
});

test('review pages remain useful without JavaScript and in print', async ({ browser }) => {
  test.skip(!selected, 'Review artifact is generated by the complete check workflow.');
  const server = await serve({ root: selected!.directory, port: 0, reviewDrafts: true });
  const origin = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
  const context = await browser.newContext({ javaScriptEnabled: false });
  try {
    const reviewData = JSON.parse(await readFile(`${selected!.directory}/data/review/resources.json`, 'utf8'));
    const affordable = reviewData.resources.filter((resource: { cost?: { state?: string } }) => ['low_cost', 'subsidized', 'mixed'].includes(resource.cost?.state ?? ''));
    const drafts = reviewData.resources.filter((resource: { publication_status: string }) => resource.publication_status === 'draft');
    const page = await context.newPage(); await page.goto(`${origin}/affordable-food/`);
    if (drafts.length) await expect(page.locator('#draft-review-banner')).toBeVisible();
    await expect(page.locator('#resource-list article')).toHaveCount(affordable.length);
    await page.goto(`${origin}/directory/download.html`); await expect(page.locator('article')).toHaveCount(reviewData.resources.length); await expect(page.locator('.draft-badge')).toHaveCount(drafts.length);
    await page.emulateMedia({ media: 'print' }); await expect(page.locator('.draft-badge').first()).toBeVisible();
  } finally { await context.close(); await new Promise<void>(resolve => server.close(() => resolve())); }
});
