// SPDX-License-Identifier: MPL-2.0
export const copy = {
  skip: 'Skip to directory', home: 'Food directory', eyebrow: 'Local food access', headline: 'Find food. Know what to expect.',
  introduction: 'Food-access services, practical details, and published schedules in your community.',
  warning: 'Published schedules do not mean live availability. Food, spaces and opening times can change. Check with the provider before travelling.',
  example: 'Fictional example — these services do not exist. This site demonstrates Food Help.',
  directory: 'Find a food resource', all: 'All resources', search: 'Search by name, service or area', category: 'Type of support',
  scheduledFilter: 'Open by published schedule', location: 'Sort using my location', clearLocation: 'Forget my location',
  locationNotice: 'Location stays in memory on this device. Distance is straight-line, not a travel route.', locationFailed: 'Location was unavailable. You can still browse every resource.',
  nearest: 'Approximate distance', resourceCount: (n: number) => `${n} resource${n === 1 ? '' : 's'}`, noResults: 'No resources match. Try another search or type of support.',
  provider: 'Provided by', address: 'Location', area: 'Service area', phone: 'Phone', eligibility: 'Who can use this', limitations: 'Limitations', before: 'Before you go',
  access: 'Access requirements', details: 'Details and sources', schedule: 'Published schedule', timezone: 'Local timezone', cost: 'Cost', languages: 'Service languages',
  unknown: 'Not confirmed', yes: 'Yes', no: 'No', walkIn: 'Walk-ins accepted', appointment: 'Appointment required', registration: 'Registration required', identification: 'Identification required',
  conditions: { active: 'Operating service', temporarily_changed: 'Service temporarily changed', temporarily_unavailable: 'Service temporarily unavailable', closed: 'Closed' },
  verification: { confirmed: 'Reviewed and confirmed', partially_confirmed: 'Some information unconfirmed', needs_review: 'Needs review' },
  methods: { provider_source: 'Provider source reviewed', direct_confirmation: 'Direct confirmation', multiple_sources: 'Multiple sources reviewed', other_reviewed: 'Other reviewed evidence' },
  categories: { prepared_meals: 'Prepared meals', food_banks_pantries: 'Food banks and pantries', groceries: 'Groceries', community_fridges: 'Community fridges', community_markets: 'Community markets', community_gardens: 'Community gardens', food_delivery: 'Food delivery', food_access_support: 'Food-access support', other_food_access: 'Other food-access services' },
  weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], closed: 'No service by published schedule', nextDay: '(next day)',
  scheduled: { scheduled_now: 'Open by published schedule', not_scheduled_now: 'Outside published hours or currently unavailable', unknown: 'Check hours with the provider' },
  scheduleKinds: { weekly: 'Weekly schedule', dated: 'Dated schedule', by_arrangement: 'Contact provider to arrange', unknown: 'Hours not confirmed' },
  validity: 'Schedule date range', exceptions: 'Date-specific changes', unconfirmed: 'Unconfirmed', reviewed: 'Last reviewed', updated: 'Information updated', overdue: 'Review overdue — confirm details before travelling.',
  source: 'Official website', sources: 'Evidence and provenance', checked: 'Source checked', supports: 'Supports', call: 'Call provider', directions: 'Directions', resourcePage: 'Resource page',
  notices: 'Temporary notices', noticePeriod: 'Notice dates', report: 'Suggest a correction', noDetails: 'Not specified. Check with the provider.',
  simple: 'Simple and printable directory', download: 'Download the directory', downloadNote: 'Save this HTML file for a self-contained offline copy. It contains the information and source dates at download time.',
  methodology: 'How information is reviewed', methodologyText: 'Resources are published only after operator review. Evidence records identify sources, review dates and the facts they support. Unknown access rules remain unknown. Verification records describe a review, not a promise that service is available today.',
  methodologyScope: 'Food Help includes food-access and support services. An ordinary commercial retailer is included only for a reviewed food-access programme. Automated validation checks structure and consistency; a person must approve the facts and publication.',
  reviewInterval: (days: number) => `The operator aims to review information every ${days} days. Older information is marked for rechecking.`,
  holidayText: 'Local date warnings require provider confirmation. Food Help does not infer holiday closures.', holidayCoverage: 'Local date-warning coverage through',
  privacy: 'Privacy', privacyText: 'Browsing requires no account or cookies. Fonts and application assets are hosted here. Search and filters stay on your device. Optional location is used in memory for sorting and is not stored or sent by Food Help. Following a provider, phone or directions link opens the service you choose.',
  privacyOffline: 'This browser may retain the application and its most recent validated public dataset for offline use. Browser settings can clear this storage. Browsers can also evict it, so offline availability cannot be guaranteed indefinitely.',
  analyticsOff: 'Analytics collection is disabled.', analyticsOn: 'Optional usage collection', analyticsExplanation: 'Only configured aggregate event types are sent. No search text, filter choices, provider identity, location, visitor identifier or activity history is included. Network requests necessarily reach the configured operator endpoint; the operator is responsible for its logging and retention.',
  analyticsPreference: 'Allow anonymous usage events', analyticsPreferenceNote: 'This preference is stored locally. Global Privacy Control and Do Not Track always disable collection.',
  about: 'About this directory', maintained: 'Maintained by', software: 'Built with Food Help', licenses: 'Licences and data rights', softwareLicense: 'Application source: Mozilla Public License 2.0.', fontLicense: 'Atkinson Hyperlegible Next: SIL Open Font License 1.1.', dataLicense: 'Resource data rights', json: 'Public JSON dataset',
  saved: 'Validated directory saved for offline use.', cached: 'Showing the last saved validated directory. Check its review dates.', network: 'Showing the latest validated directory.', unavailable: 'A fresh dataset could not be loaded. The published page remains available below.',
  savingFailed: 'The current directory is available, but this browser could not save it for offline use.', appReady: 'Application ready for offline use.', appFailed: 'Offline setup was unavailable. Basic browsing still works.', offline: 'You are offline. Check review dates; details may have changed.',
  install: 'Install Food Help', installHelp: 'Use your browser’s Install app or Add to Home Screen option. Visit online once to save the directory, then check the offline-ready message.',
  updateReady: 'An application update is ready. Apply it when you are ready to reload this page.', update: 'Apply update', updateFailed: 'The update could not be applied. Your current directory is still available.',
  refresh: 'Refresh directory', usage: 'Public usage', usageIntro: 'Sanitized totals for this deployment. These are event counts, not unique people or measures of demand. Missing totals are shown as unavailable.',
  usagePeriod: 'Reporting period', usageGenerated: 'Aggregate prepared', usageMissing: 'Unavailable',
  usageCounts: { page_starts: 'Page starts', call_actions: 'Call actions', directions_actions: 'Directions actions', source_link_actions: 'Source-link actions', installation_signals: 'Installation signals' },
  notFound: 'Page not found', notFoundText: 'Return to the directory to find a published resource.',
} as const;
export type Copy = typeof copy;
