// SPDX-License-Identifier: MPL-2.0
import { createHash } from 'node:crypto';
import { copy as c } from '../../src/copy/en.ts';
import { card, escape as e, resourcePath } from '../../src/presentation.ts';
import type { PublicDataset, Site, Usage } from '../../src/types.ts';
export const digest = (input: string | Uint8Array): string => createHash('sha256').update(input).digest('hex');
export type Page = { path: string; title: string; description: string; body: string; indexable: boolean; jsonld?: unknown };
export type Assets = { js: string; css: string[]; logo: string; icon192: string; icon512: string; font: string; brand: string };
export function pages(site: Site, data: PublicDataset, usage?: Usage): Page[] {
  const cta = `<p><a href="/directory/">${c.simple}</a> · <a href="/directory/download.html" download>${c.download}</a></p>`;
  const warning = `<p class="notice">${c.warning}</p>`;
  const resources = data.resources.map(r => card(r, data, site)).join('');
  const listData = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: site.site_name, url: `${site.canonical_origin}/`, description: site.description, mainEntity: { '@type': 'ItemList', itemListElement: data.resources.map((r, index) => ({ '@type': 'ListItem', position: index + 1, url: site.canonical_origin + resourcePath(r.id), name: r.name })) } };
  const output: Page[] = [{ path: '/', title: site.site_name, description: site.description, indexable: true, jsonld: listData, body: `<section class="hero"><div><p class="eyebrow">${c.eyebrow} · ${e(site.community.name)}</p><h1>${c.headline}</h1><p class="hero-lead">${c.introduction}</p>${cta}</div><aside class="help-panel"><div><h2>${c.before}</h2><p>${c.warning}</p>${site.help_contact ? `<a data-event="call" href="tel:${e(site.help_contact.phone)}">${e(site.help_contact.label)}</a><p>${e(site.help_contact.description ?? '')}</p>` : ''}</div></aside></section><section class="directory-shell" aria-labelledby="directory-heading"><div class="section-heading"><h2 id="directory-heading">${c.directory}</h2><p class="dataset-status" id="data-status" role="status"></p></div><div id="filters" class="filters" hidden><label class="search-control"><span>${c.search}</span><input id="search" type="search" autocomplete="off"></label><label>${c.category}<select id="category"><option value="">${c.all}</option>${Object.entries(c.categories).map(([key, label]) => `<option value="${key}">${label}</option>`).join('')}</select></label><label class="check-control"><input id="scheduled" type="checkbox">${c.scheduledFilter}</label>${site.location?.enabled ? `<button id="locate" class="button button-secondary">${c.location}</button><button id="forget-location" class="button button-quiet" hidden>${c.clearLocation}</button><p id="location-status" role="status"></p>` : ''}<button id="refresh" class="button button-quiet">${c.refresh}</button></div><p class="result-status" id="result-status" role="status">${c.resourceCount(data.resources.length)}</p><div class="resource-list" id="resource-list">${resources}</div></section>` }];
  for (const r of data.resources) {
    const organization = data.organizations.find(o => o.id === r.organization_id)!;
    const url = site.canonical_origin + resourcePath(r.id);
    const service = { '@type': 'Service', '@id': `${url}#service`, name: r.name, description: r.summary, url, serviceType: r.categories.map(cat => c.categories[cat]), provider: { '@type': 'Organization', name: organization.name, ...(organization.url ? { url: organization.url } : {}) }, ...(r.service_area ? { areaServed: r.service_area } : {}), ...(r.location?.address ? { availableChannel: { '@type': 'ServiceChannel', serviceLocation: { '@type': 'Place', name: r.location.description, address: { '@type': 'PostalAddress', streetAddress: r.location.address.street, addressLocality: r.location.address.locality, addressRegion: r.location.address.region, addressCountry: r.location.address.country, ...(r.location.address.postal_code ? { postalCode: r.location.address.postal_code } : {}) } } } } : {}) };
    output.push({ path: resourcePath(r.id), title: `${r.name} | ${site.site_name}`, description: r.summary, indexable: true, body: warning + card(r, data, site, true) + cta, jsonld: { '@context': 'https://schema.org', '@type': 'WebPage', name: r.name, description: r.summary, url, inLanguage: r.content_language ?? data.content_language, dateModified: r.updated_on, mainEntity: service, citation: r.evidence.flatMap(item => item.url ? [item.url] : []) } });
  }
  output.push({ path: '/directory/', title: `${c.simple} | ${site.site_name}`, description: site.description, indexable: false, body: `<h1>${c.simple}</h1>${warning}${cta}<p>${c.downloadNote}</p>${data.resources.map(r => card(r, data, site, false, 2).replace('<details>', '<details open>')).join('')}` });
  const page = (path: string, title: string, body: string, indexable = true) => output.push({ path, title: `${title} | ${site.site_name}`, description: `${title}. ${site.description}`, body: `<h1>${title}</h1>${body}`, indexable });
  page('/methodology/', c.methodology, `<p>${c.methodologyText}</p><p>${c.methodologyScope}</p><p>${c.reviewInterval(site.review.interval_days)}</p>${warning}<p>${c.holidayText}</p>${site.jurisdiction ? `<p>${c.holidayCoverage}: ${e(site.jurisdiction.coverage_through)}</p><ul>${site.jurisdiction.warning_dates.map(item => `<li>${e(item.date)}: ${e(item.note)} <a href="${e(item.source_url)}" rel="noreferrer">${c.source}</a> (${c.checked}: ${e(item.checked_on)})</li>`).join('')}</ul>` : ''}<p><a href="/data/v1/resources.json">${c.json}</a></p>`);
  page('/privacy/', c.privacy, `<p>${c.privacyText}</p><p>${c.privacyOffline}</p>${site.analytics?.enabled ? `<h2>${c.analyticsOn}</h2><p>${e(site.analytics.disclosure)}</p><p>${c.analyticsExplanation}</p><p>${e(new URL(site.analytics.endpoint!).origin)}</p><label><input id="analytics-preference" type="checkbox" disabled>${c.analyticsPreference}</label><p>${c.analyticsPreferenceNote}</p>` : `<p>${c.analyticsOff}</p>`}`);
  page('/about/', c.about, `<p>${e(site.description)}</p><p>${c.maintained}: ${e(site.operator.name)}</p><p>${e(site.operator.statement ?? '')}</p><p><a href="mailto:${e(site.corrections.email)}">${c.report}</a></p><p>${c.software}</p>${site.software_source_url ? `<p><a href="${e(site.software_source_url)}">${e(site.software_source_url)}</a></p>` : ''}`);
  page('/licenses/', c.licenses, `<p>${c.softwareLicense} <a href="/licenses/MPL-2.0.txt">MPL-2.0</a></p><p>${c.fontLicense} <a href="/licenses/OFL.txt">OFL</a></p><h2>${c.dataLicense}</h2><p>${e(site.data_rights.statement)}</p>${site.data_rights.url ? `<a href="${e(site.data_rights.url)}">${e(site.data_rights.license ?? site.data_rights.url)}</a>` : ''}`);
  if (usage) page('/usage/', c.usage, `<p>${c.usageIntro}</p><p>${c.usagePeriod}: ${e(usage.period_start)} – ${e(usage.period_end)}</p><p>${c.usageGenerated}: ${e(usage.generated_at)}</p><dl>${Object.entries(usage.counts).map(([key, value]) => `<dt>${c.usageCounts[key as keyof typeof c.usageCounts]}</dt><dd>${value === null ? c.usageMissing : new Intl.NumberFormat(site.locale).format(value)}</dd>`).join('')}</dl>`, false);
  page('/404.html', c.notFound, `<p>${c.notFoundText}</p>`, false);
  return output;
}
export function document(page: Page, site: Site, assets: Assets, production: boolean, standaloneCSS?: string): string {
  const index = production && !site.example_content && site.indexing?.enabled === true && page.indexable;
  const json = page.jsonld ? JSON.stringify(page.jsonld).replace(/</g, '\\u003c').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029') : '';
  const standalone = standaloneCSS !== undefined;
  return `<!doctype html><html lang="${e(site.language)}" dir="${e(site.text_direction)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(page.title)}</title><meta name="description" content="${e(page.description)}"><meta name="robots" content="${index ? 'index,follow' : 'noindex,follow'}"><link rel="canonical" href="${e(site.canonical_origin + page.path)}"><meta property="og:type" content="website"><meta property="og:title" content="${e(page.title)}"><meta property="og:description" content="${e(page.description)}"><meta property="og:url" content="${e(site.canonical_origin + page.path)}"><meta property="og:image" content="${e(site.canonical_origin + assets.icon512)}"><meta name="theme-color" content="${e(site.branding?.colors?.primary ?? '#173f4c')}">${standalone ? `<style>${standaloneCSS}</style>` : `<link rel="icon" href="${assets.logo}"><link rel="manifest" href="/manifest.webmanifest">${[...assets.css, assets.brand].map(css => `<link rel="stylesheet" href="${css}">`).join('')}<script type="module" src="${assets.js}"></script>`}${json ? `<script type="application/ld+json">${json}</script>` : ''}</head><body><a class="skip-link" href="#main" tabindex="0">${c.skip}</a><header class="site-header"><div class="header-inner"><a class="brand" href="/"><img src="${standalone ? '' : assets.logo}" ${standalone ? 'hidden' : ''} width="44" height="44" alt="">${e(site.site_name)}</a>${site.help_contact ? `<a class="header-help" data-event="call" href="tel:${e(site.help_contact.phone)}">${e(site.help_contact.label)}</a>` : ''}</div></header><main id="main">${site.example_content ? `<p class="notice example-notice">${c.example}</p>` : ''}${page.body}</main><footer class="site-footer"><nav aria-label="${c.about}">${[['/', c.home], ['/directory/', c.simple], ['/methodology/', c.methodology], ['/privacy/', c.privacy], ['/about/', c.about], ['/licenses/', c.licenses], ['/data/v1/resources.json', c.json], ...(site.public_usage?.enabled ? [['/usage/', c.usage]] : [])].map(([href, label]) => `<a href="${href}">${label}</a>`).join(' · ')}</nav><p><a href="mailto:${e(site.corrections.email)}">${c.report}</a></p>${site.emergency_contact ? `<p><a href="tel:${e(site.emergency_contact.phone)}">${e(site.emergency_contact.label)}</a> ${e(site.emergency_contact.description ?? '')}</p>` : ''}${standalone ? '' : `<p>${c.installHelp}</p><button class="button button-secondary" id="install" hidden>${c.install}</button><p id="connection-status" role="status"></p><p id="app-status" role="status"></p><div id="update-notice" class="update-notice" hidden><p>${c.updateReady}</p><button id="apply-update" class="button button-primary">${c.update}</button></div>`}</footer></body></html>`;
}
export function securityHeaders(html: string, site: Site, production: boolean): Record<string, string> {
  const hashes = [...html.matchAll(/<(script|style)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/g)].filter(item => item[2]).map(item => `'sha256-${createHash('sha256').update(item[2]!).digest('base64')}'`);
  const endpoint = site.analytics?.enabled ? ` ${new URL(site.analytics.endpoint!).origin}` : '';
  const policy = `default-src 'none'; script-src 'self' ${hashes.join(' ')}; style-src 'self' ${hashes.join(' ')}; img-src 'self' data:; font-src 'self'${html.includes('data:font/woff2;base64,') ? ' data:' : ''}; connect-src 'self'${endpoint}; manifest-src 'self'; worker-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'none'`;
  return { 'Content-Security-Policy': policy, 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer', 'X-Frame-Options': 'DENY', 'Permissions-Policy': `geolocation=${site.location?.enabled ? '(self)' : '()'}, camera=(), microphone=(), payment=()`, ...(production ? { 'Strict-Transport-Security': 'max-age=31536000' } : {}), 'Cache-Control': 'no-cache' };
}
