// SPDX-License-Identifier: MPL-2.0
import { copy as c } from './copy/en.ts';
import type { Resource, PublicDataset, Site } from './types.ts';
export const escape = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);
export const resourcePath = (id: string): string => `/resources/${id}/`;
export const list = (items: readonly string[]): string => items.length ? `<ul>${items.map(item => `<li>${escape(item)}</li>`).join('')}</ul>` : `<p>${c.noDetails}</p>`;
export function address(resource: Resource): string { return resource.location?.address ? Object.values(resource.location.address).join(', ') : resource.location?.description ?? resource.service_area ?? c.unknown; }
export function schedule(resource: Resource, site: Site, headingLevel = 5): string {
  const s = resource.schedule;
  const times = (items: typeof s.weekly[number]['intervals']) => items.map(item => `${escape(item.opens)}–${escape(item.closes)} ${item.closes_next_day ? c.nextDay : ''}`).join(', ');
  return `<p>${c.scheduleKinds[s.kind]}${s.confirmed ? '' : ` — ${c.unconfirmed}`}. ${escape(s.note)}</p><p>${c.timezone}: ${escape(resource.time_zone ?? site.time_zone)}</p>${s.valid_from || s.valid_to ? `<p>${c.validity}: ${escape(s.valid_from ?? c.unknown)} – ${escape(s.valid_to ?? c.unknown)}</p>` : ''}${s.weekly.length ? `<ul>${s.weekly.map(day => `<li>${c.weekdays[day.day - 1]}: ${day.state === 'unknown' ? c.unknown : day.state === 'closed' ? c.closed : times(day.intervals)}</li>`).join('')}</ul>` : ''}${s.exceptions.length ? `<h${headingLevel}>${c.exceptions}</h${headingLevel}><ul>${s.exceptions.map(item => `<li>${escape(item.date)}: ${item.confirmed ? (times(item.intervals) || c.closed) : c.unconfirmed}. ${escape(item.note)}</li>`).join('')}</ul>` : ''}`;
}
export function card(resource: Resource, data: PublicDataset, site: Site, full = false, headingLevel = full ? 1 : 3): string {
  const r = resource, org = data.organizations.find(item => item.id === r.organization_id)!;
  const field = (title: string, value: string) => `<section><h${headingLevel + 1}>${title}</h${headingLevel + 1}>${value}</section>`;
  const detail = `${field(c.schedule, schedule(r, site, headingLevel + 2))}${field(c.access, `<dl>${(['walk_in', 'appointment_required', 'registration_required', 'identification_required'] as const).map((key, i) => `<dt>${[c.walkIn, c.appointment, c.registration, c.identification][i]}</dt><dd>${c[r.access[key]]}</dd>`).join('')}</dl>${list(r.access.details)}`)}${field(c.eligibility, list(r.eligibility))}${field(c.limitations, list(r.limitations))}${field(c.before, list(r.before_you_go))}${r.cost ? field(c.cost, `<p>${escape(r.cost.description)}</p>`) : ''}${r.service_languages?.length ? field(c.languages, list(r.service_languages)) : ''}${r.notices?.length ? field(c.notices, list(r.notices.map(item => `${item.text} (${c.noticePeriod}: ${item.starts_on} – ${item.ends_on ?? c.unknown})`))) : ''}${field(c.sources, `<ul>${r.evidence.map(e => `<li>${e.url ? `<a data-event="source" href="${escape(e.url)}" rel="noreferrer">${escape(e.url)}</a>` : escape(c.methods.direct_confirmation)}<p>${c.checked}: <time>${escape(e.checked_on)}</time>. ${escape(e.note)}</p><p>${c.supports}: ${escape(e.supports.join(', '))}</p></li>`).join('')}</ul><p>${c.methods[r.verification.method]}. ${c.verification[r.verification.state]}.</p>`)}`;
  const level = `h${headingLevel}`;
  return `<article class="resource-card" data-resource-id="${escape(r.id)}" lang="${escape(r.content_language ?? data.content_language)}"><div class="card-header"><div><div class="tags">${r.categories.map(cat => `<span class="tag">${c.categories[cat]}</span>`).join('')}</div><${level}>${full ? escape(r.name) : `<a href="${resourcePath(r.id)}">${escape(r.name)}</a>`}</${level}><p class="operator">${c.provider} ${escape(org.name)}</p></div></div><p class="summary">${escape(r.summary)}</p><p>${escape(r.food_access_purpose)}</p><p class="availability" data-schedule-status>${c.warning}</p><p>${c.conditions[r.service_condition]}</p><dl class="card-facts"><div class="fact"><dt>${c.address}</dt><dd>${escape(address(r))}</dd></div>${r.phone ? `<div class="fact"><dt>${c.phone}</dt><dd>${escape(r.phone)}${r.phone_extension ? ` ${escape(r.phone_extension)}` : ''}</dd></div>` : ''}</dl>${full ? `<div class="detail-grid">${detail}</div>` : `<details><summary>${c.details}</summary><div class="detail-grid">${detail}</div></details>`}<div class="card-actions">${r.phone ? `<a class="button button-primary" data-event="call" href="tel:${escape(r.phone)}${r.phone_extension ? `;ext=${r.phone_extension}` : ''}">${c.call}</a>` : ''}${r.location?.address ? `<a class="button button-secondary" data-event="directions" rel="noreferrer" href="https://www.openstreetmap.org/search?query=${encodeURIComponent(address(r))}">${c.directions}</a>` : ''}${r.official_url ? `<a class="button button-secondary" data-event="source" rel="noreferrer" href="${escape(r.official_url)}">${c.source}</a>` : ''}</div><p class="verified">${c.reviewed}: <time>${escape(r.verification.reviewed_on)}</time> · ${c.updated}: <time>${escape(r.updated_on)}</time></p><p data-review-warning></p></article>`;
}
